rtest.tos: test.o clear.o clr_reg.o
	cc68x -g test.o clear.o clr_reg.o -o rtest.tos

test.o: test.c raster.h
	cc68x -g -c test.c

clear.o: clear.s
	cc68x -g -c clear.s

clr_reg.o: clr_reg.s
	cc68x -g -c clr_reg.s
